// reactapp/src/components/InputError.tsx
export const InputError = ({ error }) => {
  return (
    <div
      className="flex items-center bg-red-300 bg-opacity-80 rounded-sm p-1.5 gap-2 w-full mb-2"
      id="name-error"
    >
      <svg
        className="text-red-600 size-5"
        xmlns="http://www.w3.org/2000/svg"
        width="1em"
        height="1em"
        viewBox="0 0 1024 1024"
      >
        <path
          fill="currentColor"
          d="M512 64a448 448 0 1 1 0 896a448 448 0 0 1 0-896m0 832a384 384 0 0 0 0-768a384 384 0 0 0 0 768m48-176a48 48 0 1 1-96 0a48 48 0 0 1 96 0m-48-464a32 32 0 0 1 32 32v288a32 32 0 0 1-64 0V288a32 32 0 0 1 32-32"
        />
      </svg>
      <span className="block text-red-500 text-base">{error}</span>
    </div>
  );
};

// svelteapp/src/lib/Form/InputError.svelte
<!-- <div class="flex items-center bg-red-300 bg-opacity-80 rounded-sm p-1.5 gap-2 hidden" id="name-error"> -->
<div class="flex items-center bg-red-300 bg-opacity-80 rounded-sm p-1.5 gap-2" id="name-error">
    <svg class="text-red-600 size-5" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
      viewBox="0 0 1024 1024">
      <path fill="currentColor"
        d="M512 64a448 448 0 1 1 0 896a448 448 0 0 1 0-896m0 832a384 384 0 0 0 0-768a384 384 0 0 0 0 768m48-176a48 48 0 1 1-96 0a48 48 0 0 1 96 0m-48-464a32 32 0 0 1 32 32v288a32 32 0 0 1-64 0V288a32 32 0 0 1 32-32" />
    </svg>
    <span class="block text-red-500 text-base">Error Message</span>
  </div>
